version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=docup
      - POSTGRES_PASSWORD=docup2005
      - POSTGRES_DB=task_manager
    volumes:
      - task_manager_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_PATH=/configs/configs.ini
    ports:
      - "8080:8080"
    volumes:
      - ./configs:/configs
      - ./output:/output
    depends_on:
      - db
    command: ["java", "-jar", "/app/TGbot.jar", "autostart"]

volumes:
  task_manager_db_data:
