version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=docup
      - POSTGRES_PASSWORD=docup2005
      - POSTGRES_DB=task_manager
    volumes:
      - task_manager_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Монтируем файл init.sql для автоматического выполнения
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_PATH=/configs/configs.ini
    ports:
      - "8080:8080"
    volumes:
      - ./configs:/configs
      - ./output:/output
    depends_on:
      - db
    networks:
      - app_network
    command: ["java", "-jar", "/app/TGbot.jar", "autostart"]

volumes:
  task_manager_db_data:

networks:
  app_network:
    driver: bridge
